sonar.projectKey=VictorBonnin_DockerProjet-Pitwall
sonar.organization=victorbonnin

sonar.projectName=PitWall
sonar.projectVersion=0.1.0

sonar.sources=lib,app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,.next/**,public/**,prisma/**,workers/**,scripts/**
sonar.coverage.exclusions=tests/**,workers/**,scripts/**,app/**,lib/db/**
sonar.cpd.exclusions=tests/**

sonar.sourceEncoding=UTF-8
